### ISSUE TITLE
Video Embed

### ISSUE THREAD

**Issue by dyoungwd** [kororaproject/kp-documentation#1]
Currently we can not embed Vimeo videos into the Korora-Install-How-To.md file as it is not supported.

A fix I have done is

`[![Korora_Project_-_2017-06-14_22.18.13.png](https://s30.postimg.org/6ujhi1i6p/Korora_Project_-_2017-06-14_22.18.13.png)](https://vimeo.com/69508041)`

This uses an image of the video then links. It may be possible to link a youtube vid but not yet confirmed.

**Comment by jimkp** [comment]
Currently there is only one video guide and it was considered a temporary fix until a better installation was created. So I wouldn't consider it a serious loss.

However as video is a popular format for guides it is something that we need a fix for long term. If we confirm one video provider works we can include that in our contribution guide.

**Comment by dyoungwd** [comment]
will try using script tag to embed and I believe youtube may work but need to check on that also
