### ISSUE TITLE
Add TOC to articles

### ISSUE THREAD

**Issue by AdmiralAsshat** [kororaproject/kp-documentation#4]
It may benefit the longer articles to have a Table of Contents for quick navigation, and to make the headings and subheadings more clear.

To convert the existing inventory, we can try adding by hand, or finding some programmatic way of adding them. I've tried using [doctoc](https://github.com/thlorenz/doctoc), which has the advantage of being able to convert an entire repo in one fell swoop, but it adds some unpleasant watermarks and comments that I would prefer to remove. See below on sample article I ran it against:

`

**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [Working with Archives](#working-with-archives)
  - [Archive Types and Extensions](#archive-types-and-extensions)
    - [Tar](#tar)
    - [Zip](#zip)
  - [Within the File Manager](#within-the-file-manager)
    - [Creating an Archive](#creating-an-archive)
    - [Extracting an Archive](#extracting-an-archive)
  - [Within the Terminal](#within-the-terminal)
    - [Creating an Archive](#creating-an-archive-1)
    - [Extracting an Archive](#extracting-an-archive-1)

`

If we're otherwise happy with it, I can probably write a sed command to remove all HTML comment lines and any line containing "DocToc" without too much trouble. But it also inserts the TOC at the top of the article, whereas it is traditionally below the H1. So we'd need to rearrange those, too.

**Comment by jimkp** [comment]
The only issue I see is that the website doesn't support internal links, at least not that I am aware of, so any TOC would be passive there. 

If we decide to use the wiki in place of the current site then it would work well.

I don't believe the placement is an issue as I don't think the leading H1 is needed, reviewing the document referenced on the wiki shows that the H1 is a repeat of the title.

**Comment by AdmiralAsshat** [comment]
> The only issue I see is that the website doesn't support internal links, at least not that I am aware of, so any TOC would be passive there.

The links that are generated are in-line, I believe, within the Markdown itself. It's in the process of compiling the Markdown to HTML that the URL becomes absolute. So whether it works on the website or not would depend on whether the website does the Markdown rendering or if it only stores the final HTML.

Take a look at my fork [here](https://github.com/AdmiralAsshat/kp-documentation) where I've run DocToc and see if it looks agreeable. You can check the Raw on any given article to see the HTML comments as well. As I said, I can probably remove those and the watermark before submitting a Pull.

**Comment by dyoungwd** [comment]
I had a look at the pages where you have implemented DocToc and see it uses div id. Will have to try it out in the wiki first. When u use relative links in the repo they do not work in the wiki for example a link in the repo - ./Some-Page.md in the wiki would goto github.com/Some-Page.

Never used ( or heard of)  DocToc so do you need to run it before every push and does it add to every page automatically? 

Considering our pages are not that big at present and assuming div id links will work in the wiki is there any benefit of using this over just simply hand coding on pages that are slightly larger?

**Comment by AdmiralAsshat** [comment]
> I had a look at the pages where you have implemented DocToc and see it uses div id.

I believe that's in keeping consistent with Markdown itself. If you look at any page rendered in Github Markdown and hover to the left of a section header, you'll get a hyperlink popup with a URL to that specific header via a generated div ID.

> Never used ( or heard of) DocToc so do you need to run it before every push and does it add to every page automatically?

Needs to be run manually.

>Considering our pages are not that big at present and assuming div id links will work in the wiki is there any benefit of using this over just simply hand coding on pages that are slightly larger?

I'm not crazy about node.js myself--the primary purpose was simply in converting our existing inventory of articles quickly. For future articles, I would think perhaps we could add the suggestion of TOC into the submissions guidelines and add them by hand.

I have updated my repo to remove the HTML comments and the DocToc watermark via some simple commands:
`sed -i 's/\*generated.*$//g' *.md`
`sed -i 's/<[^>]*>//g' *.md`

Took only a few minutes to DocToc on the whole set and the additional commands to clean them up, so no big loss if we don't want to go that route. But if you're happy with the results otherwise, I can submit a Pull request.

**Comment by jimkp** [comment]
After some experimentation I've found it is possible to have a TOC on the website. See https://kororaproject.org/support/documentation/which-desktop-for-your-korora. See the code used at https://github.com/kororaproject/kp-documentation/blob/master/GettingKorora/Which-Desktop-for-Your-Korora.md. It still needs testing with child documents.
This makes the use of a TOC practical and useful

**Comment by jimkp** [comment]
After some further testing I found the TOC generated by DocToc doesn't work on the website. the website need html after the heading e.g. `<a name="Applications"></a>` for the link in the TOC to work.
